version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build banana/banana.csproj
  test:
    steps:
      - run:
          name: DOTNET TEST
          command: echo Tests go here.
# workflows:
#   sat_cd:
#     jobs:
#       - build
#           # filter:
#           #   branches:
#           #     only:
#           #       - develop
#           #       - /feature.*/
#       - test
